name: appoint_buddy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  meta: ^1.15.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.3.0
  email_otp_auth: ^1.1.0
  equatable: ^2.0.7
  marquee: ^2.3.0
  table_calendar: ^3.0.8
  intl: ^0.20.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/videos/
    - assets/fonts/
    - assets/images/
